### ISSUE TITLE
humanus infusion missing

### ISSUE THREAD

**Issue by EdC94** [TheDrunkMafia/ThaumicInfusion#35]
Using the last version (4.18), the humanus aspect seems to be missing in the focus GUI, I have not tested on 4.17, the already infused blocks are still infused and working.

Also, the issue is older but the humanus infused blocks don't seem to remember that they are infused clientside but they do serverside and disconecting/ reconnecting seem to fix it until I go away then the issue pop again when I come back.

**Comment by TheDrunkMafia** [comment]
Check your configs, the only time that it does not show up in the gui is when the aspect has not been registered on the client.

**Comment by EdC94** [comment]
that's strange considering that there was no change in the config since before the update but i will check nonetheless

**Comment by EdC94** [comment]
the humanus effect is set on true in the thaumic infusion config, I will check if i have the same issue with an older version of thaumic infusion

**Comment by TheDrunkMafia** [comment]
I've just updated the mod on curse forge, try the new version. I've not really changed anything to do with how aspects are picked up & rendered in the UI, however there is always a chance I cleaned something up & it got fixed.

**Comment by EdC94** [comment]
well, i just checked in single player without changing version and all the the aspect are here but in multiplayer humanus, and i just noticed permutatio too, seems to be missing... The config should be the same so I have no idea what's going on here... o_O I'm not admin and my friend who is has gone to sleep so i will ask him to update tomorow and i'll see if the issue is still here

**Comment by TheDrunkMafia** [comment]
Just to make sure, you have got the aspect in question researched on the server? If you don't then it wont turn up as a valid infusion, since you don't know about it.

**Comment by EdC94** [comment]
yes, i've researched all aspects. Moreover, it was me who infused those blocks, so I'm pretty sure i should still be able to do it.

**Comment by EdC94** [comment]
Same crash as: https://github.com/TheDrunkMafia/ThaumicInfusion/issues/36 with 4.19

**Comment by EdC94** [comment]
Ok, this bug keep getting stranger as time pass, we haven't done the update yet and today Humanus and Permutatio are back but it's Sano that's missing...
I'll ask my friend to update the server to 4.20 and see if something change

**Comment by EdC94** [comment]
no change with 4.20 the Sano infusion is still missing

**Comment by TheDrunkMafia** [comment]
Sounds like some of the aspects are being skipped during the page creation, it's random since Thaumcraft does not store the aspects in a specific order. I'll review the code & apply a fix.

**Comment by TheDrunkMafia** [comment]
Try this version: https://dl.dropboxusercontent.com/u/101919880/Thaumic%20Infusion/ThaumicInfusion-4.21.jar I want to make sure that it's all working.

**Comment by EdC94** [comment]
No change, Sano aspect still missing

**Comment by TheDrunkMafia** [comment]
Done some testing & I seemed to have found the issue, it was to do with the algorithm that sorts the aspects into a grid. It was rounding the number required to calculate the size of each Column. If you are able, try this build & if it is working I will release it on curseforge. https://dl.dropboxusercontent.com/u/101919880/Thaumic%20Infusion/ThaumicInfusion-4.21.jar

**Comment by EdC94** [comment]
sorry, still no change, sano is still missing

**Comment by EdC94** [comment]
By the way, we have other mods that add aspects, that could be one cause of the bug

**Comment by EdC94** [comment]
Still the same bug with 4.25, and it's Victus that's missing this time

**Comment by Alaberti** [comment]
Is this fixed in the latest release?

**Comment by TheDrunkMafia** [comment]
I don't know, in my development environment its is present. So I can only assume that it has been fixed.

**Comment by TheDrunkMafia** [comment]
I can only assume that this has been fixed, since In all my testing I can't seem to recreate this. However soon I will be re-working the GUI, so hopefully it will be fixed completely.
